version: '3.8'
services:
  web: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
# Using 2.0 https://hub.docker.com/_/influxdb
  influxdb: 
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin 
      - DOCKER_INFLUXDB_INIT_PASSWORD=mynewpassword
      - DOCKER_INFLUXDB_INIT_ORG=dimes
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    restart: always

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    links:
      - influxdb
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always
